## 탐색적 데이터 분석
### 포아송분포

다음은 한남대학교 정문을 통과하는 차량의 수가 Poisson 분포를 따르는지 알아보
기 위하여 1분마다 차량 통과 회수를 300회 조사하였다. 아래 자료를 이용하여
Poisson 분포를 따르는지 검정하시오. (유의수준=0.05)

| - | - | - | - | - | - | - | - | - | 
| :---: | :---: | :---: | :---: | :---: | :--: | - | - | - |
| 분 | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 
| 관측빈도 | 20 | 54 | 74 | 67 | 47 | 25 | 11 | 4 | 


In [59]:
import numpy as np
import pandas as pd
import scipy.stats
import math

In [3]:
x = np.asarray([20,54,74,67,45,25,11,4])
n = np.asarray([0,1,2,3,4,5,6,7])
lm = sum(n*x)/sum(x)

In [16]:
np.random.poisson(lm,7)

array([3, 1, 2, 1, 1, 1, 4])

In [97]:
p = list(range(0,8))
for i in range(8):
    p[i] = (math.exp(-lm)*lm**i)/math.factorial(i)

In [122]:
p = np.asarray(p)
p

array([0.06902177, 0.1845182 , 0.24663932, 0.21978304, 0.14688833,
       0.07853629, 0.03499228, 0.01336372])

In [133]:
e = sum(x)*p
e

array([20.70653066, 55.35545863, 73.99179637, 65.93491188, 44.06649944,
       23.56088837, 10.49768471,  4.00911578])

In [142]:
(x[0]-e[0])**2/e[0]

0.02410763934066284

In [144]:
T = list(range(0,8))
for i in range(8):
    T[i] = (x[i]-e[i])**2/e[i]

In [147]:
1-sum(T)

0.7937625832510817

In [149]:
p_values = 1-scipy.stats.chi2.cdf(sum(T),3)
p_values

0.9765761394755619